### ISSUE TITLE
Version 1.0.1 broken when using retrofit2 release version

### ISSUE THREAD

**Issue by AlexGrafl** [vimeo/vimeo-networking-java#107]
As the 1.0.1 version uses the retrofit2-beta3 build, it will not work when using the retrofit2 release version (currently 2.1.0) as there have been changes to the converter package name.
It will fail when intializing the VimeoClient with a NoClassDefFoundError:
`FATAL EXCEPTION: main
Process: de.meinestadt.talenthero, PID: 29389
java.lang.NoClassDefFoundError: Failed resolution of: Lretrofit2/GsonConverterFactory;
at com.vimeo.networking.VimeoClient.createRetrofit(VimeoClient.java:120)
at com.vimeo.networking.VimeoClient.<init>(VimeoClient.java:112)
at com.vimeo.networking.VimeoClient.initialize(VimeoClient.java:101)
at de.meinestadt.talenthero.TalentHeroApp.onCreate(TalentHeroApp.java:35)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
at android.app.ActivityThread.-wrap1(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.ClassNotFoundException: Didn't find class "retrofit2.GsonConverterFactory" on path: DexPathList[[zip file "/data/app/de.meinestadt.talenthero-2/base.apk"],nativeLibraryDirectories=[/data/app/de.meinestadt.talenthero-2/lib/arm, /data/app/de.meinestadt.talenthero-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
at com.vimeo.networking.VimeoClient.createRetrofit(VimeoClient.java:120) 
at com.vimeo.networking.VimeoClient.<init>(VimeoClient.java:112) 
at com.vimeo.networking.VimeoClient.initialize(VimeoClient.java:101) 
at de.meinestadt.talenthero.TalentHeroApp.onCreate(TalentHeroApp.java:35) 
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013) 
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707) 
at android.app.ActivityThread.-wrap1(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:148) 
at android.app.ActivityThread.main(ActivityThread.java:5417) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
Suppressed: java.lang.ClassNotFoundException: retrofit2.GsonConverterFactory
at java.lang.Class.classForName(Native Method)
at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
... 15 more`

Looking into the source, it seems the package name of the GsonConverterFactory changed from 'retrofit2' to 'retrofit2.converter.gson' and therfore it will throw an exception when trying to intialize.

On the 1.1.0 branch, it seems to be fixed, as the retrofit2 release version was used, when is it going to be released?

**Comment by kevinzetterstrom** [comment]
Hi @AlexGrafl 
1.1.0 will be released in the next few weeks. We will keep this ticket open until then and post back here to let you know.

**Comment by Onwa1kenobi** [comment]
I also have this problem and we've been waiting since July. any news on this?

**Comment by kevinzetterstrom** [comment]
This is currently in our queue, sorry for the trouble but stay tuned!

**Comment by kevinzetterstrom** [comment]
@AlexGrafl @Onwa1kenobi v1.1.0 is now published and available on jCenter. Closing this issue for that reason. If you have any other issues, don't hesitate to let us know!

**Comment by Onwa1kenobi** [comment]
Noted @kevinzetterstrom, thank you.
