### ISSUE TITLE
Problem with proguard and GsonDeserializer class

### ISSUE THREAD

**Issue by yshahak** [vimeo/vimeo-networking-java#144]
I tried to implement the library in conjunction with _proGuard_.
I copied the **GsonDeserializer.class** from the example and handed it to the **Configuration.Builder class.** 
When _proGuard_ is off, everything is working perfect. When _ProGuard_ is on, the app crashed with the following log:

Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:309)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.AssertionError: java.lang.NoSuchFieldException: NOBODY
       at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.(SourceFile)
       at com.google.gson.internal.bind.TypeAdapters$30.create(SourceFile:834)
       at com.google.gson.Gson.getAdapter(SourceFile:423)
       at com.google.gson.Gson.getAdapter(SourceFile:521)
       at com.vimeo.stag.generated.Stag.readFromAdapter(SourceFile:69)
       at com.vimeo.stag.generated.ParseUtils.parsePrivacy(SourceFile:4757)
       at com.vimeo.stag.generated.ParseUtils.parseVideo(SourceFile:1991)
       at com.vimeo.stag.generated.Stag$VideoAdapter.read(SourceFile:807)
       at com.vimeo.stag.generated.Stag$VideoAdapter.read(SourceFile:793)
       at com.vimeo.stag.generated.Stag.readListFromAdapter(SourceFile:85)
       at com.vimeo.stag.generated.ParseUtils.parseArray(SourceFile:67)
       at com.vimeo.stag.generated.ParseUtils.parseVideoList(SourceFile:4838)
       at com.vimeo.stag.generated.Stag$VideoListAdapter.read(SourceFile:537)
       at com.vimeo.stag.generated.Stag$VideoListAdapter.read(SourceFile:523)
       at com.google.gson.Gson.fromJson(SourceFile:887)
       at com.google.gson.Gson.fromJson(SourceFile:852)
       at com.google.gson.Gson.fromJson(SourceFile:801)
       at com.google.gson.Gson.fromJson(SourceFile:773)

I tried to add this lines to _proGuard_ rules:
`-keep class com.ysapps.videoplayer.AndroidGsonDeserializer

-keepclassmembers class * implements com.vimeo.networking.GsonDeserializer {
    <fields>;
}

-keepnames class * implements com.vimeo.networking.GsonDeserializer`

But it not solved the issue.

**Comment by kevinzetterstrom** [comment]
Since this library doesn't have any Android dependencies, we haven't included an official ProGuard file.  You will have to include lines for Retrofit, Gson, and this library. The following has worked on demo projects in the past, let us know if it helps you.

```
## BEGIN RETROFIT
-dontwarn retrofit2.**
-keep class retrofit2.** { *; }
-keepattributes Signature
-keepattributes Exceptions
## END RETROFIT


## BEGIN VIMEO-NETWORKING
-dontwarn javax.annotation.**
-dontwarn javax.inject.**
-dontwarn sun.misc.Unsafe
## END VIMEO-NETWORKING


## BEGIN GSON
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-keep class sun.misc.Unsafe { *; }
-keep class com.google.gson.** { *; }

# Application classes that will be serialized/deserialized over Gson
-keep class com.vimeo.networking.** { *; }
-keepclassmembers enum * { *; }

## END GSON
```

**Comment by kevinzetterstrom** [comment]
By the way, the last line about enums should help fix the crash you experienced.

**Comment by yshahak** [comment]
Yes. It solved the issue! Thanks for the help, it was really fast.
