### ISSUE TITLE
Providing a user agent with a ™️ character in it causes crash

### ISSUE THREAD

**Issue by anthonycr** [vimeo/vimeo-networking-java#273]
#### Issue Summary
Passing certain characters as the user agent to the networking library causes a crash. The crash is internally caused by (https://github.com/square/okhttp/blob/parent-3.9.1/okhttp/src/main/java/okhttp3/Headers.java#L324).

#### Reproduction Steps
Pass a non ascii character as the user agent, e.g. `™️`. Then make a network request and observe the crash.

#### Expected Behavior
I would expect either the crash not to occur OR the `setUserAgentString` to throw an exception if the user agent is not valid.

#### Actual Behavior
```
java.lang.IllegalArgumentException: Unexpected char 0x2122 at 62 in User-Agent value: com.vimeo.android.videoapp (Trapress.net/MYTPRO Dev., Trapress™ MYTab, google, Android 4.4.2/19 Version 2.17.0) VimeoNetworking/2.0.0-alpha.4 (Java)
	at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:320)
	at okhttp3.Headers$Builder.set(Headers.java:300)
	at okhttp3.Request$Builder.header(Request.java:164)
	at com.vimeo.networking.interceptors.UserAgentInterceptor.intercept(UserAgentInterceptor.java:52)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at com.vimeo.networking.logging.LoggingInterceptor.intercept(LoggingInterceptor.java:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
```

**Comment by anthonycr** [comment]
Fixed by https://github.com/vimeo/vimeo-networking-java/pull/287
