### ISSUE TITLE
VimeoError on fetchContent() request with incorrect system date on device on Android Oreo

### ISSUE THREAD

**Issue by Alexey-Batishchev** [vimeo/vimeo-networking-java#288]
#### Issue Summary
When I tried to make fetchContent() request with incorrect system date, I got the     com.vimeo.networking.model.error.VimeoError, Chain validation failed. It reproduces on android Oreo. For previous versions vimeo sdk works correct.

The same behavior I see in Vimeo android app.

Sdk version : vimeo-networking:1.1.1.                                                                   

#### Reproduction Steps

Device:all
OS: Android oreo
Steps:
1. Go to device setting and set future date (next week or mounth).
2. Make any api call to vimeo using vimeo sdk.
3. Receive the error.

#### Expected Behavior
API should work without errors as on previous android versions.

#### Actual Behavior
I got the error VimeoError with message "Chain validation failed"
   com.vimeo.networking.model.error.VimeoError
                                                                            at com.vimeo.networking.callbacks.VimeoCallback.onFailure(VimeoCallback.java:86)
                                                                            at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$2.run(ExecutorCallAdapterFactory.java:77)
                                                                            at android.os.Handler.handleCallback(Handler.java:789)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                            at android.os.Looper.loop(Looper.java:172)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6637)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by KChernenko** [comment]
Guys, we have the same issue.

**Comment by msya** [comment]
@Alexey-Batishchev @KChernenko The issue is occurring because SSL certificate pinning does not play nicely with setting a future date. Okhttp will throw a handshake exception. You could turn off SSL certificate pinning by calling `setCertPinningEnabled` on the configuration object e.g. `configuration.setCertPinningEnabled(false)`.
