### ISSUE TITLE
JsonSyntaxException: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $

### ISSUE THREAD

**Issue by ricardopereira** [vimeo/vimeo-networking-java#385]
#### Issue Summary

I want to know the link of a Video ID that I have in the database but an error occurs when deserializing the object.

I'm using the latest stable version (`implementation "com.vimeo.networking:vimeo-networking:1.1.3"`). It's an Android project with Kotlin.

#### Reproduction Steps

Just try to fetch the content of a Video like:

``` kotlin
VimeoClient.getInstance().fetchNetworkContent("/videos/"+id, object : ModelCallback<Video>(Video::class.java) {

    override fun success(video: Video) {
        onSuccess(video, videoInfo, directory, fetch)
    }

    override fun failure(error: VimeoError) {
        Timber.e(error.exception,"Vimeo download error occurred ${error.developerMessage}")
    }

})
```

#### Expected Behavior

A deserialized `Video` object where I can use it and access the video link.

#### Actual Behavior

A `com.google.gson.JsonSyntaxException` exception occurs:

``` console
I/System.out: --------- RESPONSE ---------
I/System.out: ENDPOINT: /videos/<redacted>
    STATUS CODE: 200
I/System.out: REQUEST TIME: 1322.8ms
I/System.out: --------- RESPONSE END ---------
I/System.out: Error when deserializing object!
W/System.err: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $
        at com.google.gson.Gson.fromJson(Gson.java:900)
W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:853)
        at com.google.gson.Gson.fromJson(Gson.java:802)
        at com.google.gson.Gson.fromJson(Gson.java:774)
        at com.vimeo.networking.GsonDeserializer.deserializeObject(GsonDeserializer.java:66)
        at com.vimeo.networking.GsonDeserializer.deserialize(GsonDeserializer.java:58)
        at com.vimeo.networking.VimeoClient$5.success(VimeoClient.java:1169)
        at com.vimeo.networking.callbacks.VimeoCallback.onResponse(VimeoCallback.java:55)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6762)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
    Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $
        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:825)
        at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.read(TypeAdapters.java:799)
        at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.read(TypeAdapters.java:772)
```

From the stack trace you can see it fails in https://github.com/vimeo/vimeo-networking-java/blob/cce993401c336f473b021d9ff65d709ac23b43e1/vimeo-networking/src/main/java/com/vimeo/networking/GsonDeserializer.java#L66.

**Comment by msya** [comment]
@ricardopereira Thanks for bringing this issue to our attention. I have opened a PR #386 to resolve it. It should be merged soon. I'll have a fix out for you very soon.

**Comment by msya** [comment]
@ricardopereira May I know what is the video id that you are trying to get.

**Comment by ricardopereira** [comment]
@msya Sure, it's ~~`325674692`~~`328720584`.

**Comment by ricardopereira** [comment]
@msya Any news about this? Can I help on something? Thanks.

**Comment by ricardopereira** [comment]
@msya Here is the JSON response where the GSON deserializer can't map into a `Video` object:

```
{"uri":"/videos/328720584","name":"Coach Module III Part V - Session (Final)","type":"video","link":"https://vimeo.com/328720584","duration":3629.0,"width":1920.0,"height":1080.0,"embed":{"buttons":{"like":false,"watchlater":false,"share":false,"embed":false,"hd":false,"fullscreen":true,"scaling":true},"logos":{"vimeo":false,"custom":{"active":false,"sticky":false}},"title":{"name":"hide","owner":"hide","portrait":"hide"},"playbar":true,"volume":true,"speed":false,"color":"00adef","uri":"/presets/120201391","html":"\u003ciframe src\u003d\"https://player.vimeo.com/video/328720584?badge\u003d0\u0026autopause\u003d0\u0026player_id\u003d0\u0026app_id\u003d77380\" width\u003d\"1920\" height\u003d\"1080\" frameborder\u003d\"0\" title\u003d\"Coach Module III Part V - Session (Final)\" allow\u003d\"autoplay; fullscreen\" allowfullscreen\u003e\u003c/iframe\u003e","badges":{"hdr":false,"live":{"streaming":false,"archived":false},"staff_pick":{"normal":false,"best_of_the_month":false,"best_of_the_year":false,"premiere":false},"vod":false,"weekend_challenge":false}},"created_time":"2019-04-05T19:15:25+00:00","modified_time":"2019-04-08T18:01:10+00:00","release_time":"2019-04-05T19:15:25+00:00","content_rating":["unrated"],"privacy":{"view":"disable","embed":"whitelist","download":false,"add":false,"comments":"nobody"},"pictures":{"uri":"/videos/328720584/pictures/773312675","active":true,"type":"custom","sizes":[{"width":100.0,"height":75.0,"link":"https://i.vimeocdn.com/video/773312675_100x75.jpg?r\u003dpad","link_with_play_button":"https://i.vimeocdn.com/filter/overlay?src0\u003dhttps%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F773312675_100x75.jpg\u0026src1\u003dhttp%3A%2F%2Ff.vimeocdn.com%2Fp%2Fimages%2Fcrawler_play.png"},{"width":200.0,"height":150.0,"link":"https://i.vimeocdn.com/video/773312675_200x150.jpg?r\u003dpad","link_with_play_button":"https://i.vimeocdn.com/filter/overlay?src0\u003dhttps%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F773312675_200x150.jpg\u0026src1\u003dhttp%3A%2F%2Ff.vimeocdn.com%2Fp%2Fimages%2Fcrawler_play.png"},{"width":295.0,"height":166.0,"link":"https://i.vimeocdn.com/video/773312675_295x166.jpg?r\u003dpad","link_with_play_button":"https://i.vimeocdn.com/filter/overlay?src0\u003dhttps%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F773312675_295x166.jpg\u0026src1\u003dhttp%3A%2F%2Ff.vimeocdn.com%2Fp%2Fimages%2Fcrawler_play.png"},{"width":640.0,"height":360.0,"link":"https://i.vimeocdn.com/video/773312675_640x360.jpg?r\u003dpad","link_with_play_button":"https://i.vimeocdn.com/filter/overlay?src0\u003dhttps%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F773312675_640x360.jpg\u0026src1\u003dhttp%3A%2F%2Ff.vimeocdn.com%2Fp%2Fimages%2Fcrawler_play.png"},{"width":960.0,"height":540.0,"link":"https://i.vimeocdn.com/video/773312675_960x540.jpg?r\u003dpad","link_with_play_button":"https://i.vimeocdn.com/filter/overlay?src0\u003dhttps%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F773312675_960x540.jpg\u0026src1\u003dhttp%3A%2F%2Ff.vimeocdn.com%2Fp%2Fimages%2Fcrawler_play.png"},{"width":1280.0,"height":720.0,"link":"https://i.vimeocdn.com/video/773312675_1280x720.jpg?r\u003dpad","link_with_play_button":"https://i.vimeocdn.com/filter/overlay?src0\u003dhttps%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F773312675_1280x720.jpg\u0026src1\u003dhttp%3A%2F%2Ff.vimeocdn.com%2Fp%2Fimages%2Fcrawler_play.png"},{"width":1920.0,"height":1080.0,"link":"https://i.vimeocdn.com/video/773312675_1920x1080.jpg?r\u003dpad","link_with_play_button":"https://i.vimeocdn.com/filter/overlay?src0\u003dhttps%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F773312675_1920x1080.jpg\u0026src1\u003dhttp%3A%2F%2Ff.vimeocdn.com%2Fp%2Fimages%2Fcrawler_play.png"},{"width":1280.0,"height":720.0,"link":"https://i.vimeocdn.com/video/773312675_1280x720.jpg?r\u003dpad","link_with_play_button":"https://i.vimeocdn.com/filter/overlay?src0\u003dhttps%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F773312675_1280x720.jpg\u0026src1\u003dhttp%3A%2F%2Ff.vimeocdn.com%2Fp%2Fimages%2Fcrawler_play.png"}],"resource_key":"990751fb7dc948e9a2800c9b0e21f7cd1f350cd8"},"tags":[],"stats":{"plays":1812.0},"metadata":{"connections":{"comments":{"uri":"/videos/328720584/comments","options":["GET","POST"],"total":0.0},"credits":{"uri":"/videos/328720584/credits","options":["GET","POST"],"total":1.0},"likes":{"uri":"/videos/328720584/likes","options":["GET"],"total":0.0},"pictures":{"uri":"/videos/328720584/pictures","options":["GET","POST"],"total":1.0},"texttracks":{"uri":"/videos/328720584/texttracks","options":["GET","POST"],"total":0.0},"versions":{"uri":"/videos/328720584/versions","options":["GET"],"total":1.0,"current_uri":"/videos/328720584/versions/221685146"}},"interactions":{"watchlater":{"uri":"/users/40828294/watchlater/328720584","options":["GET","PUT","DELETE"],"added":false},"report":{"uri":"/videos/328720584/report","options":["POST"],"reason":["pornographic","harassment","advertisement","ripoff","incorrect rating","spam"]}}},"user":{"uri":"/users/40828294","name":"Brian Johnson","link":"https://vimeo.com/user40828294","created_time":"2015-06-05T20:35:51+00:00","websites":[],"metadata":{"connections":{"activities":{"uri":"/users/40828294/activities","options":["GET"]},"albums":{"uri":"/users/40828294/albums","options":["GET"],"total":5.0},"appearances":{"uri":"/users/40828294/appearances","options":["GET"],"total":0.0},"categories":{"uri":"/users/40828294/categories","options":["GET"],"total":0.0},"channels":{"uri":"/users/40828294/channels","options":["GET"],"total":0.0},"feed":{"uri":"/users/40828294/feed","options":["GET"]},"followers":{"uri":"/users/40828294/followers","options":["GET"],"total":26.0},"following":{"uri":"/users/40828294/following","options":["GET"],"total":2.0},"groups":{"uri":"/users/40828294/groups","options":["GET"],"total":0.0},"likes":{"uri":"/users/40828294/likes","options":["GET"],"total":6.0},"moderated_channels":{"uri":"/users/40828294/channels?filter\u003dmoderated","options":["GET"],"total":0.0},"portfolios":{"uri":"/users/40828294/portfolios","options":["GET"],"total":0.0},"videos":{"uri":"/users/40828294/videos","options":["GET"],"total":4034.0},"watchlater":{"uri":"/users/40828294/watchlater","options":["GET"],"total":0.0},"shared":{"uri":"/users/40828294/shared/videos","options":["GET"],"total":0.0},"pictures":{"uri":"/users/40828294/pictures","options":["GET","POST"],"total":0.0},"watched_videos":{"uri":"/me/watched/videos","options":["GET"],"total":0.0},"block":{"uri":"/me/block","options":["GET"],"total":1.0}}},"preferences":{"videos":{"privacy":"disable"}},"content_filter":["language","drugs","violence","nudity","safe","unrated"],"resource_key":"d982844645a45f7783f6b6cfdbd6db46ff2e57bd","account":"business"},"last_user_action_event_date":"2019-04-05T19:15:25+00:00","files":[{"quality":"hd","type":"video/mp4","width":1920.0,"height":1080.0,"link":"http://player.vimeo.com/external/328720584.hd.mp4?s\u003d686d09444f54ad3caeadf66df3f57295d85f9c31\u0026profile_id\u003d175\u0026oauth2_token_id\u003d903088387","created_time":"2019-04-05T19:16:53+00:00","fps":25.0,"size":8.95148249E8,"md5":"72201c751bce13475c1704100191f450","link_secure":"https://player.vimeo.com/external/328720584.hd.mp4?s\u003d686d09444f54ad3caeadf66df3f57295d85f9c31\u0026profile_id\u003d175\u0026oauth2_token_id\u003d903088387"},{"quality":"sd","type":"video/mp4","width":960.0,"height":540.0,"link":"http://player.vimeo.com/external/328720584.sd.mp4?s\u003d2bb5a4c55dae0f536b9f4765102b31d124700ce1\u0026profile_id\u003d165\u0026oauth2_token_id\u003d903088387","created_time":"2019-04-05T19:16:53+00:00","fps":25.0,"size":3.37030493E8,"md5":"246c52c67767f7d095aaac37218ac4a2","link_secure":"https://player.vimeo.com/external/328720584.sd.mp4?s\u003d2bb5a4c55dae0f536b9f4765102b31d124700ce1\u0026profile_id\u003d165\u0026oauth2_token_id\u003d903088387"},{"quality":"hd","type":"video/mp4","width":1280.0,"height":720.0,"link":"http://player.vimeo.com/external/328720584.hd.mp4?s\u003d686d09444f54ad3caeadf66df3f57295d85f9c31\u0026profile_id\u003d174\u0026oauth2_token_id\u003d903088387","created_time":"2019-04-05T19:16:52+00:00","fps":25.0,"size":4.84596993E8,"md5":"478aafc1f0a3420e6d0626b65fd878f9","link_secure":"https://player.vimeo.com/external/328720584.hd.mp4?s\u003d686d09444f54ad3caeadf66df3f57295d85f9c31\u0026profile_id\u003d174\u0026oauth2_token_id\u003d903088387"},{"quality":"sd","type":"video/mp4","width":640.0,"height":360.0,"link":"http://player.vimeo.com/external/328720584.sd.mp4?s\u003d2bb5a4c55dae0f536b9f4765102b31d124700ce1\u0026profile_id\u003d164\u0026oauth2_token_id\u003d903088387","created_time":"2019-04-05T19:16:52+00:00","fps":25.0,"size":2.19349033E8,"md5":"9cbc3620e41e866687142de367891e7c","link_secure":"https://player.vimeo.com/external/328720584.sd.mp4?s\u003d2bb5a4c55dae0f536b9f4765102b31d124700ce1\u0026profile_id\u003d164\u0026oauth2_token_id\u003d903088387"},{"quality":"hls","type":"video/mp4","link":"https://player.vimeo.com/external/328720584.m3u8?s\u003db0ca48144a30c6076358a16aab6a32e82567d9e0\u0026oauth2_token_id\u003d903088387","created_time":"2019-04-05T19:16:53+00:00","fps":25.0,"size":8.95148249E8,"md5":"72201c751bce13475c1704100191f450","link_secure":"https://player.vimeo.com/external/328720584.m3u8?s\u003db0ca48144a30c6076358a16aab6a32e82567d9e0\u0026oauth2_token_id\u003d903088387"}],"download":[{"quality":"source","type":"source","width":1920.0,"height":1080.0,"expires":"2019-04-08T21:18:00+00:00","link":"https://player.vimeo.com/play/1288892339?s\u003d328720584_1554790680_fbb5c006201497b1289887a60302fad2\u0026loc\u003dexternal\u0026context\u003dVimeo%5CController%5CApi%5CResources%5CVideoController.\u0026download\u003d1\u0026filename\u003dCoach%2BModule%2BIII%2BPart%2BV%2B-%2BSession%2B%2528Final%2529source.mp4","created_time":"2019-04-05T19:15:25+00:00","fps":25.0,"size":3.275545575E9,"md5":"e66dbfe23f35be37ceb826157b875c56"},{"quality":"hd","type":"video/mp4","width":1920.0,"height":1080.0,"expires":"2019-04-08T21:18:00+00:00","link":"https://player.vimeo.com/play/1288893701?s\u003d328720584_1554790680_c561db7085bd8fb676325ce7091865e7\u0026loc\u003dexternal\u0026context\u003dVimeo%5CController%5CApi%5CResources%5CVideoController.\u0026download\u003d1\u0026filename\u003dCoach%2BModule%2BIII%2BPart%2BV%2B-%2BSession%2B%2528Final%2529175.mp4","created_time":"2019-04-05T19:16:53+00:00","fps":25.0,"size":8.95148249E8,"md5":"72201c751bce13475c1704100191f450"},{"quality":"sd","type":"video/mp4","width":960.0,"height":540.0,"expires":"2019-04-08T21:18:00+00:00","link":"https://player.vimeo.com/play/1288893690?s\u003d328720584_1554790680_baf1a9048ee732888e1b788e2162f339\u0026loc\u003dexternal\u0026context\u003dVimeo%5CController%5CApi%5CResources%5CVideoController.\u0026download\u003d1\u0026filename\u003dCoach%2BModule%2BIII%2BPart%2BV%2B-%2BSession%2B%2528Final%2529165.mp4","created_time":"2019-04-05T19:16:53+00:00","fps":25.0,"size":3.37030493E8,"md5":"246c52c67767f7d095aaac37218ac4a2"},{"quality":"hd","type":"video/mp4","width":1280.0,"height":720.0,"expires":"2019-04-08T21:18:00+00:00","link":"https://player.vimeo.com/play/1288893675?s\u003d328720584_1554790680_7c1ebe47864142f59b961e5cf8f2c36e\u0026loc\u003dexternal\u0026context\u003dVimeo%5CController%5CApi%5CResources%5CVideoController.\u0026download\u003d1\u0026filename\u003dCoach%2BModule%2BIII%2BPart%2BV%2B-%2BSession%2B%2528Final%2529174.mp4","created_time":"2019-04-05T19:16:52+00:00","fps":25.0,"size":4.84596993E8,"md5":"478aafc1f0a3420e6d0626b65fd878f9"},{"quality":"sd","type":"video/mp4","width":640.0,"height":360.0,"expires":"2019-04-08T21:18:00+00:00","link":"https://player.vimeo.com/play/1288893674?s\u003d328720584_1554790680_f909c9a2704713652072625391b91410\u0026loc\u003dexternal\u0026context\u003dVimeo%5CController%5CApi%5CResources%5CVideoController.\u0026download\u003d1\u0026filename\u003dCoach%2BModule%2BIII%2BPart%2BV%2B-%2BSession%2B%2528Final%2529164.mp4","created_time":"2019-04-05T19:16:52+00:00","fps":25.0,"size":2.19349033E8,"md5":"9cbc3620e41e866687142de367891e7c"}],"app":{"name":"Frame.io","uri":"/apps/92260"},"status":"available","resource_key":"b829220f99158adde932b6a512555000f1bd245e","upload":{"status":"complete"},"transcode":{"status":"complete"},"review_link":"https://vimeo.com/user40828294/review/328720584/55bcf5fbf2","embed_presets":{"uri":"/presets/120201391","name":"Master Classes","settings":{"buttons":{"like":false,"watchlater":false,"share":false,"embed":false,"vote":false,"hd":false},"logos":{"vimeo":false,"custom":false,"sticky_custom":false},"outro":"nothing","autopause":true,"autoplay":false,"background":false,"cards":[],"color":"00adef","dnt":false,"loop":false,"muted":false,"outro_secondary_link_name":"","outro_secondary_link_url":"","outro_text_title":"","link":true,"overlay_email_capture":-1.0,"overlay_email_capture_confirmation":"Thanks! We’ll be in touch.","playsinline":true,"responsive":false,"show_360_label":true,"badge":false,"byline":"hide","byline_badge":false,"collections_button":false,"show_compass":true,"fullscreen_button":true,"playbar":true,"portrait":"hide","scaling_button":true,"speed":false,"title":"hide","volume":true,"transparent":true,"color_original":false,"stream_clips":{"video":[]}},"metadata":{"connections":{"videos":{"uri":"/presets/120201391/videos","options":["GET"],"total":3104.0}}},"user":{"uri":"/users/40828294","name":"Brian Johnson","link":"https://vimeo.com/user40828294","created_time":"2015-06-05T20:35:51+00:00","websites":[],"metadata":{"connections":{"activities":{"uri":"/users/40828294/activities","options":["GET"]},"albums":{"uri":"/users/40828294/albums","options":["GET"],"total":5.0},"appearances":{"uri":"/users/40828294/appearances","options":["GET"],"total":0.0},"categories":{"uri":"/users/40828294/categories","options":["GET"],"total":0.0},"channels":{"uri":"/users/40828294/channels","options":["GET"],"total":0.0},"feed":{"uri":"/users/40828294/feed","options":["GET"]},"followers":{"uri":"/users/40828294/followers","options":["GET"],"total":26.0},"following":{"uri":"/users/40828294/following","options":["GET"],"total":2.0},"groups":{"uri":"/users/40828294/groups","options":["GET"],"total":0.0},"likes":{"uri":"/users/40828294/likes","options":["GET"],"total":6.0},"moderated_channels":{"uri":"/users/40828294/channels?filter\u003dmoderated","options":["GET"],"total":0.0},"portfolios":{"uri":"/users/40828294/portfolios","options":["GET"],"total":0.0},"videos":{"uri":"/users/40828294/videos","options":["GET"],"total":4034.0},"watchlater":{"uri":"/users/40828294/watchlater","options":["GET"],"total":0.0},"shared":{"uri":"/users/40828294/shared/videos","options":["GET"],"total":0.0},"pictures":{"uri":"/users/40828294/pictures","options":["GET","POST"],"total":0.0},"watched_videos":{"uri":"/me/watched/videos","options":["GET"],"total":0.0},"block":{"uri":"/me/block","options":["GET"],"total":1.0}}},"preferences":{"videos":{"privacy":"disable"}},"content_filter":["language","drugs","violence","nudity","safe","unrated"],"resource_key":"d982844645a45f7783f6b6cfdbd6db46ff2e57bd","account":"business"}}}
```

**Comment by ricardopereira** [comment]
@msya I found the issue while debugging in the Vimeo library. Basically the `ModelCallback` was using a wrong `Video` type. I was expecting a `com.vimeo.networking.model.Video` type but while evaluating the `callback.getObjectType()` I noticed it was using another type 😒 My bad.

**Comment by ricardopereira** [comment]
BTW

**Solution:** I forced the type like
`VimeoClient.getInstance().fetchNetworkContent("/videos/"+id, object : ModelCallback<com.vimeo.networking.model.Video>(com.vimeo.networking.model.Video::class.java) {...`

Not beautiful but it's woking 🤷‍♂️
