### ISSUE TITLE
Looks to be a server issue... again

### ISSUE THREAD

**Issue by samgherman** [vimeo/vimeo-networking-java#545]
No one responded to my ticket last time, when there was some kind of outage, although I see that this project is still being worked on. Looks like no one has closed a ticket since Aug 2021... that's not good. How can a company the size of Vimeo not have any dev support?

@anthonycr / @howardrigberg  do you do any kind of support? 

The issue:

As of today as I started getting emails from users of my app that they can no longer play videos... again. 

Appears to be a server issue... again. 

Everything loads, but it appears that the stream is corrupt or something? As you can see below there is a 410 response code when playing the video. Which appears to be...

_The HyperText Transfer Protocol (HTTP) 410 Gone client error response code indicates that access to the target resource is no longer available at the origin server and that this condition is likely to be permanent_

The Vimeo API works fine on iOS, this seems to be an Android issue.

I haven't touched my app since the last time there was an issue with the Vimeo server, everything was working fine, so this is not a problem on my end here. 

When I put the link that it spits out as what should be the download link to play the video into my browser it says 
![image](https://user-images.githubusercontent.com/23468055/159149746-aa13e419-a7c9-4551-ac40-3afea4f74ab8.png)

When I get the link that the iOS app spits out and paste it into my browser, it plays the video. 

This URL scheme, which android uses, appears to be down:
 https://player.vimeo.com/progressive_redirect/download/ ..... 

E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:579)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 410
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:383)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1015)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

**Comment by anthonycr** [comment]
Hey, please raise this with the support team https://vimeo.com/help/contact

Unfortunately, the developers (myself included) that work on this library only work on it part time and aren't API engineers, so we can't really provide consistent support in the issue tracker.
